### ISSUE TITLE
RuntimeError on Usage "python run_monodepth.py -t dpt_hybrid_kitti"

### ISSUE THREAD

**Issue by korshunovdv** [intel-isl/DPT#37]
Hi,
I just clone repo, weight and some images from KITTI dataset (put it's to /input).

![2011_09_26_drive_0002_sync_0000000075](https://user-images.githubusercontent.com/29779398/124624321-7501c900-de85-11eb-86c4-4fbbeb81a926.png)

When I use command `python run_monodepth.py -t dpt_hybrid_kitti` follow error occurred:
```bash
python run_monodepth.py -t dpt_hybrid_kitti
initialize
device: cuda
/home/dkorshunov/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
start processing
  processing input/2011_09_26_drive_0002_sync_0000000075.png (1/1)
/home/dkorshunov/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
Traceback (most recent call last):
  File "run_monodepth.py", line 237, in <module>
    args.optimize,
  File "run_monodepth.py", line 152, in run
    prediction = model.forward(sample)
  File "/media/data/experiments/DPT/dpt/models.py", line 115, in forward
    inv_depth = super().forward(x).squeeze(dim=1)
  File "/media/data/experiments/DPT/dpt/models.py", line 72, in forward
    layer_1, layer_2, layer_3, layer_4 = forward_vit(self.pretrained, x)
  File "/media/data/experiments/DPT/dpt/vit.py", line 107, in forward_vit
    glob = pretrained.model.forward_flex(x)
  File "/media/data/experiments/DPT/dpt/vit.py", line 175, in forward_flex
    x = self.patch_embed.backbone(x)
  File "/home/dkorshunov/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dkorshunov/anaconda3/envs/py37/lib/python3.7/site-packages/timm/models/resnetv2.py", line 409, in forward
    x = self.forward_features(x)
  File "/home/dkorshunov/anaconda3/envs/py37/lib/python3.7/site-packages/timm/models/resnetv2.py", line 403, in forward_features
    x = self.stem(x)
  File "/home/dkorshunov/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dkorshunov/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/dkorshunov/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dkorshunov/anaconda3/envs/py37/lib/python3.7/site-packages/timm/models/layers/std_conv.py", line 70, in forward
    self.weight.view(1, self.out_channels, -1), None, None,
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

**Comment by ranftlr** [comment]
Seems like timm received an upgrade that breaks our code. Please downgrade timm to 0.4.5 to resolve this for now:

```
pip install timm==0.4.5
```

**Comment by korshunovdv** [comment]
Thank you, it helps!
If you don't mind, I have already created pull request with `requirements.txt` and update README file, to make setup process a little bit easier. #38

**Comment by ranftlr** [comment]
Thanks a lot!
